{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-enshuman
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/enshuman_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/enshuman/enshuman_{{ version }}.tar.gz
  sha256: 3ed6c2e4563cf491a62b5e332f8aff53792bca22461c6e5a206ad2cc7e8a56a6

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('enshuman')"           # [not win]
    - "\"%R%\" -e \"library('enshuman')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=enshuman
  license: LGPL-3.0-or-later
  summary: Gene information from 'Ensembl' genome builds 'GRCh38.p14' and 'GRCh37.p13' to use
    with the 'topr' package. The datasets were originally downloaded from <https://ftp.ensembl.org/pub/current/gtf/homo_sapiens/Homo_sapiens.GRCh38.111.gtf.gz>
    and <https://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.gtf.gz>
    and converted into the format required by the 'topr' package. See <https://github.com/totajuliusd/topr?tab=readme-ov-file#how-to-use-topr-with-other-species-than-human>
    to see the required format.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# The original CRAN metadata for this package was:

# Package: enshuman
# Title: Human Gene Annotation Data from 'Ensembl'
# Version: 1.0.0
# Authors@R: c( person("Thorhildur", "Juliusdottir", role = c("cph","aut", "cre"),email = "totajuliusd@gmail.com") )
# Description: Gene information from 'Ensembl' genome builds 'GRCh38.p14' and 'GRCh37.p13' to use with the 'topr' package. The datasets were originally downloaded from <https://ftp.ensembl.org/pub/current/gtf/homo_sapiens/Homo_sapiens.GRCh38.111.gtf.gz> and <https://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.gtf.gz> and converted into the format required by the 'topr' package. See <https://github.com/totajuliusd/topr?tab=readme-ov-file#how-to-use-topr-with-other-species-than-human> to see the required format.
# License: LGPL (>= 3)
# Encoding: UTF-8
# LazyData: true
# LazyDataCompression: xz
# RoxygenNote: 7.2.3
# Suggests: testthat (>= 3.0.0), knitr, rmarkdown, markdown
# Config/testthat/edition: 3
# Imports:
# Depends: R (>= 3.5.0)
# NeedsCompilation: no
# Packaged: 2024-01-31 10:59:17 UTC; tota
# Author: Thorhildur Juliusdottir [cph, aut, cre]
# Maintainer: Thorhildur Juliusdottir <totajuliusd@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-02-02 12:40:05 UTC
