{% set version = '0.99.17' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gwasrapidd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gwasrapidd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gwasrapidd/gwasrapidd_{{ version }}.tar.gz
  sha256: 1dd21a19ea8718420809d91a7658008602a1da8b0e395e0d525691ba0fafbeba

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-concatenate
    - r-dplyr
    - r-glue
    - r-httr
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-pingr
    - r-plyr
    - r-progress
    - r-purrr
    - r-rlang
    - r-stringr
    - r-testthat
    - r-tibble
    - r-tidyr >0.8.99
    - r-urltools
    - r-writexl
  run:
    - r-base
    - r-assertthat
    - r-concatenate
    - r-dplyr
    - r-glue
    - r-httr
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-pingr
    - r-plyr
    - r-progress
    - r-purrr
    - r-rlang
    - r-stringr
    - r-testthat
    - r-tibble
    - r-tidyr >0.8.99
    - r-urltools
    - r-writexl

test:
  commands:
    - $R -e "library('gwasrapidd')"           # [not win]
    - "\"%R%\" -e \"library('gwasrapidd')\""  # [win]

about:
  home: https://github.com/ramiromagno/gwasrapidd, https://rmagno.eu/gwasrapidd/
  license: MIT
  summary: '''GWAS'' R ''API'' Data Download. This package provides easy access to the ''NHGRI''-''EBI''
    ''GWAS'' Catalog data by accessing the ''REST'' ''API'' <https://www.ebi.ac.uk/gwas/rest/docs/api/>.'
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE
# biocViews: ThirdPartyClient, BiomedicalInformatics, GenomeWideAssociation, SNP

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gwasrapidd
# Type: Package
# Title: 'REST' 'API' Client for the 'NHGRI'-'EBI' 'GWAS' Catalog
# Version: 0.99.17
# Authors@R: c( person(given = "Ramiro", family = "Magno", email = "rmagno@pattern.institute", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-5226-3441")), person(given = "Ana-Teresa", family = "Maia", email = "maia.anateresa@gmail.com", role = "aut", comment = c(ORCID = "0000-0002-0454-9207")), person("CINTESIS", role = c("cph", "fnd")), person("Pattern Institute", role = c("cph", "fnd")) )
# Description: 'GWAS' R 'API' Data Download. This package provides easy access to the 'NHGRI'-'EBI' 'GWAS' Catalog data by accessing the 'REST' 'API' <https://www.ebi.ac.uk/gwas/rest/docs/api/>.
# Depends: R (>= 3.2.3)
# License: MIT + file LICENSE
# URL: https://github.com/ramiromagno/gwasrapidd, https://rmagno.eu/gwasrapidd/
# BugReports: https://github.com/ramiromagno/gwasrapidd/issues
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 7.2.3
# Imports: magrittr, httr, urltools, pingr, stringr, concatenate, dplyr, jsonlite, purrr, tibble, glue, tidyr (> 0.8.99), assertthat, rlang, methods, lubridate, plyr, testthat, utils, progress, writexl
# Suggests: httptest, spelling, covr, knitr, rmarkdown, bookdown
# Collate: 'browser.R' 'class-associations.R' 'class-studies.R' 'class-traits.R' 'class-variants.R' 'data.R' 'ebi_server.R' 'generics.R' 'get_associations.R' 'get_metadata.R' 'get_studies.R' 'get_traits.R' 'get_variants.R' 'gwasrapidd-package.R' 'id_mapping.R' 'list_joins.R' 'missing.R' 'parse-associations.R' 'parse-studies.R' 'parse-traits.R' 'parse-utils.R' 'parse-variants.R' 'post-studies.R' 'post-traits.R' 'post-variants.R' 'recursive_apply.R' 'request.R' 's4-utils.R' 'sure.R' 'tests.R' 'utils-pipe.R' 'utils.R' 'write_xlsx.R'
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2023-12-15 16:42:18 UTC; rmagno
# Author: Ramiro Magno [aut, cre] (<https://orcid.org/0000-0001-5226-3441>), Ana-Teresa Maia [aut] (<https://orcid.org/0000-0002-0454-9207>), CINTESIS [cph, fnd], Pattern Institute [cph, fnd]
# Maintainer: Ramiro Magno <rmagno@pattern.institute>
# Repository: CRAN
# Date/Publication: 2023-12-15 21:50:08 UTC
