{% set version = '1.1-2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ebnm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ebnm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ebnm/ebnm_{{ version }}.tar.gz
  sha256: 29783634a60a0e552997396f9d25566ec938ee9133923795428bf377414a1493

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ashr
    - r-deconvolver
    - r-dplyr
    - r-ggplot2
    - r-horseshoe
    - r-magrittr
    - r-mixsqp
    - r-rlang
    - r-truncnorm
    - r-trust
  run:
    - r-base
    - r-ashr
    - r-deconvolver
    - r-dplyr
    - r-ggplot2
    - r-horseshoe
    - r-magrittr
    - r-mixsqp
    - r-rlang
    - r-truncnorm
    - r-trust

test:
  commands:
    - $R -e "library('ebnm')"           # [not win]
    - "\"%R%\" -e \"library('ebnm')\""  # [win]

about:
  home: https://github.com/stephenslab/ebnm
  license: GPL-3.0-only
  summary: Provides simple, fast, and stable functions to fit the normal means model using empirical
    Bayes. For available models and details, see function ebnm(). A detailed introduction
    to the package is provided by Willwerscheid and Stephens (2021) <arXiv:2110.00152>.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ebnm
# Encoding: UTF-8
# Type: Package
# Version: 1.1-2
# Date: 2023-10-12
# Title: Solve the Empirical Bayes Normal Means Problem
# Authors@R: c(person("Jason", "Willwerscheid", role = "aut"), person("Matthew", "Stephens", role = "aut"), person("Peter", "Carbonetto", role = c("aut", "cre"), email = "peter.carbonetto@gmail.com"), person("Andrew", "Goldstein", role = "ctb"), person("Yusha", "Liu", role = "ctb"))
# URL: https://github.com/stephenslab/ebnm
# BugReports: https://github.com/stephenslab/ebnm/issues
# Description: Provides simple, fast, and stable functions to fit the normal means model using empirical Bayes. For available models and details, see function ebnm(). A detailed introduction to the package is provided by Willwerscheid and Stephens (2021) <arXiv:2110.00152>.
# License: GPL (>= 3)
# NeedsCompilation: no
# Depends: R (>= 3.3.0)
# Imports: stats, ashr, mixsqp, truncnorm, trust, horseshoe, deconvolveR, magrittr, rlang, dplyr, ggplot2
# Suggests: testthat, numDeriv, REBayes, knitr, rmarkdown, cowplot
# RoxygenNote: 7.2.3
# VignetteBuilder: knitr
# LazyData: true
# Packaged: 2023-10-12 17:28:03 UTC; pcarbo
# Author: Jason Willwerscheid [aut], Matthew Stephens [aut], Peter Carbonetto [aut, cre], Andrew Goldstein [ctb], Yusha Liu [ctb]
# Maintainer: Peter Carbonetto <peter.carbonetto@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-10-12 21:10:02 UTC
